site_name: Purview Automation

theme:
  name: material
  language: en

nav:
  - index.md
  - Why This Library: why-this-library.md
  - Tutorial  - User Guide:
    - First Steps: tutorial/first-steps.md
    - Create a Purview Resource: tutorial/create-purview.md
    - Authenticate and Connect with Purview: tutorial/authenticate-connect.md
    - List Collections: tutorial/list-collections.md
    - Create Collections: tutorial/create-collections.md
    - Delete Collections: tutorial/delete-collections.md
    - Delete Collections Recursively: tutorial/delete-collections-recursively.md
    - Get Collection Name: tutorial/get-collection-name.md
    
plugins:
  - search
  - mkdocstrings

repo_url: https://github.com/Ludwinic1/purviewautomation

markdown_extensions:
  - admonition



