name: Create Purview 

on: workflow_dispatch

jobs:
  create-purview-account:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
      
      - name: Create Purview Account 
        uses: azure/powershell@v1 
        with:
          azPSVersion: latest 
          inlineScript: |
            Install-Module Az.Purview -Force
            Import-Module Az.Purview
            $L = [Char[]]'abcdefghijklmnopqrstuvwxyz'
            $PurviewAccountName = (Get-Random -Count 10 -InputObject $L) -join ''
            New-AzPurviewAccount -Name "$PurviewAccountName" -ResourceGroupName {{ secrets.RG_NAME }} -Location {{ secrets.PURVIEW_LOCATION }} -IdentityType SystemAssigned -SkuCapacity 4 -SkuName Standard -PublicNetworkAccess {{ secrets.NETWORK_ACCESS }}

      # RUN THE PYTEST SCRIPT
      # Then delete the Purview account. 




